name: Unit tests
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - uses: actions/setup-node@v4
        name: Setup node.js
        with:
          node-version: 22

      - uses: pnpm/action-setup@v4
        name: Setup pnpm
        with:
          version: 10

      - run: pnpm i
        name: Install dependencies

      - run: pnpm test
        name: Run unit tests

      - run: pnpm build
        name: Check build
