name: Unit tests
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - uses: actions/setup-node@v4
        name: Setup node.js
        with:
          node-version: 22

      - run: npm ci
        name: Install dependencies

      - run: npm test
        name: Run unit tests

      - run: npm run build
        name: Check build
